// <auto-generated />
using Client.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Client.Data.Migrations
{
    [DbContext(typeof(ClientEntities))]
    [Migration("20190819110957_112")]
    partial class _112
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Client.Model.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(500);

                    b.Property<string>("ClientEmail")
                        .HasMaxLength(500);

                    b.Property<string>("ClientName")
                        .HasMaxLength(500);

                    b.Property<string>("Mobile")
                        .HasMaxLength(50);

                    b.Property<string>("WebSite");

                    b.HasKey("ClientId");

                    b.ToTable("Client");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Address = "5 - 17 paradaise - October Gardens - Giza",
                            ClientEmail = "mattia@eggate.com",
                            ClientName = "Mostafa Attia",
                            Mobile = "+201008346362",
                            WebSite = "N.A"
                        },
                        new
                        {
                            ClientId = 2,
                            Address = "Maadi",
                            ClientEmail = "mnagy@eggate.com",
                            ClientName = "Mahmoud Nagy",
                            Mobile = "+201119849089",
                            WebSite = "N.A"
                        },
                        new
                        {
                            ClientId = 3,
                            Address = "6th of October City",
                            ClientEmail = "aelkady@eggate.com",
                            ClientName = "Ahmed Elkady",
                            Mobile = "+201017413234",
                            WebSite = "N.A"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
